### ISSUE TITLE
Hitting the max number of readers is not well handled for LMDB

### ISSUE THREAD

**Issue by willemolding** [holochain/holochain-persistence#14]
An error from Holochain core

```
thread '<unnamed>' panicked at 'failed to fetch from CAS: ErrorGeneric("CAS fetch error: lmdb error: MDB_READERS_FULL: Environment maxreaders limit reached")', src/libcore/result.rs:1051:5
stack backtrace:
   0:     0x559ea879428b - backtrace::backtrace::libunwind::trace::hd4effc5cbc99af65
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x559ea879428b - backtrace::backtrace::trace_unsynchronized
::h389cccb5967fa3c2
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x559ea879428b - std::sys_common::backtrace::_print::hbb606689fb98322f
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x559ea879428b - std::sys_common::backtrace::print::h2b6171d791ff1fac
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x559ea879428b - std::panicking::default_hook::{{closure}}::h7c4f6f6170cc3cf6
                               at src/libstd/panicking.rs:200
   5:     0x559ea8793f67 - std::panicking::default_hook::hd9f23e1c4cbbedcb
                               at src/libstd/panicking.rs:214
   6:     0x559ea8794a00 - std::panicking::rust_panic_with_hook::h7fedb25d8f7a616a
                               at src/libstd/panicking.rs:477
   7:     0x559ea8794582 - std::panicking::continue_panic_fmt::hed2a79ffb3c5014c
                 
              at src/libstd/panicking.rs:384
   8:     0x559ea8794466 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x559ea87b865d - core::panicking::panic_fmt::hcd868b6ef07f5b76
                               at src/libcore/panicking.rs:85
  10:     0x559ea86dde1b - core::result::unwrap_failed::h1a9d12edfaef88d6
  11:     0x559ea7e33238 - core::result::Result<T,E>::expect::h2141151a6071296f
  12:     0x559ea7e3450c - <holochain_core::agent::chain_store::ChainStoreIterator as core::iter::traits::iterator::Iterator>::next::hfbb33c38d1702709
  13:     0x559ea7f1497e - holochain_core::network::handler::get_content_aspect::h51276c5c2d74e8de
  14:     0x559ea7e5e43f - holochain_core::network::handler::lists::get_all_aspect_addresses::h0f51605409be3502
  15:     0x559ea7e456c3 - <F as threadpool::FnBox>::call_box::hdcba862d07a64de7
  16:     0x559ea7f7491b - std::sys_common::backtrace::__rust_begin_short_backtrace::he184ede26c2ba82c
  17:     0x559ea879fb3a - __rust_maybe_catch_panic
```

**Comment by willemolding** [comment]
From the rkv-lmdb docs on `max+readers`

> This defines the number of slots in the lock table that is used to track readers in the the environment. The default is 126. Starting a read-only transaction normally ties a lock table slot to the current thread until the environment closes or the thread exits. If MDB_NOTLS is in use, Environment::open_txn instead ties the slot to the Transaction object until it or the Environment object is destroyed.

The question is how are we tying up 126 readers under normal operations?!
